version: "3.9"
services:
  avito:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
        - db
  db:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "avito"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"